import Submission.AbelianVariety.Rigidity

/-!
# Uniqueness in the universal property of the Jacobian (Albanese)

Tower C.  Hole 9 (`Jacobian.exists_unique_ofCurve_comp`) asserts that a pointed
morphism `f : C ⟶ A` from a curve to an abelian variety factors **uniquely** through
the Jacobian as a homomorphism `g` with `f = ofCurve P ≫ g`.  Round 1 supplied the
*existence-side rigidity* input (`isMonHom_of_pointed_of_geometricallyIntegral`: the
factoring map is forced to be a homomorphism).  This file supplies the **uniqueness**
half as ready-to-wire abelian-variety theory.

The mechanism is classical (Milne, *Jacobian Varieties* §6; Mumford, *Abelian
Varieties* §4): a homomorphism out of the Jacobian is determined by its composite with
the Abel–Jacobi map, because the iterated sums of that map generate the Jacobian.  We
formalize it as two genuine, general pieces and assemble them:

* `hom_ext_of_isDominant` — **a morphism of `k`-schemes is determined by its restriction
  to a (topologically) dominant subscheme**, when the source is reduced and the target is
  separated over `k`.  For abelian varieties (target proper ⟹ separated, source integral
  ⟹ reduced) this is the uniqueness engine.  *Discharged on arbitrary data.*
* `postcompHom` — **postcomposition by a homomorphism of group objects is a group
  homomorphism `Hom(W, J) →* Hom(W, A)` of Hom-groups** (`MonObj.one_comp` /
  `MonObj.mul_comp`), so it carries finite sums of the Abel–Jacobi map to finite sums of
  its composite.  *Discharged on arbitrary data.*
* `albanese_uniqueness` — assembles the two: if the iterated sums of `φ` generate `J`
  (the geometric *generation* input, supplied by Tower B as a dominant sum-morphism),
  then two homomorphisms agreeing after `φ` are equal.

The only input not discharged here is the genuine geometric fact that the curve generates
the Jacobian (`IsDominant` of an iterated-sum morphism) — Tower B's `Jacobian C = Pic⁰ C`
and `ofCurve` instantiate it; the integrator wires it.

No `sorry`, no `axiom`.
-/

open CategoryTheory Limits MonoidalCategory CartesianMonoidalCategory MonObj

namespace AbelianVariety

universe u

open AlgebraicGeometry

variable {K : Type u} [Field K]

/-! ### Determination of a morphism by a dominant subscheme -/

/-- **A morphism of `k`-schemes is determined by its restriction to a (topologically)
dominant subscheme**, when the source `J` is reduced and the target `A` is separated over
`k` (e.g. proper).  This is the uniqueness mechanism of the Albanese universal property:
the source is the Jacobian (an integral variety, hence reduced) and the target is an
abelian variety (proper, hence separated). -/
theorem hom_ext_of_isDominant {J A : Over (Spec (.of K))} [IsReduced J.left] [IsProper A.hom]
    {W : Over (Spec (.of K))} (u : W ⟶ J) [IsDominant u.left]
    {g₁ g₂ : J ⟶ A} (h : u ≫ g₁ = u ≫ g₂) : g₁ = g₂ := by
  refine Over.OverMorphism.ext (ext_of_isDominant_of_isSeparated A.hom ?_ u.left ?_)
  · rw [Over.w, Over.w]
  · rw [← Over.comp_left, ← Over.comp_left, h]

/-! ### Postcomposition by a homomorphism is a homomorphism of Hom-groups -/

variable {M N : Over (Spec (.of K))} [MonObj M] [MonObj N]

/-- **Postcomposition by a homomorphism of group (monoid) objects is a monoid
homomorphism of Hom-groups** `Hom(W, M) →* Hom(W, N)`.  Concretely `a ↦ a ≫ g`; it
preserves the identity (`MonObj.one_comp`) and the product (`MonObj.mul_comp`), so it
sends a finite sum `∏ᵢ aᵢ` to `∏ᵢ (aᵢ ≫ g)`. -/
@[simps]
noncomputable def postcompHom (g : M ⟶ N) [IsMonHom g] (W : Over (Spec (.of K))) :
    (W ⟶ M) →* (W ⟶ N) where
  toFun a := a ≫ g
  map_one' := MonObj.one_comp g
  map_mul' a b := MonObj.mul_comp a b g

/-! ### Uniqueness in the Albanese universal property -/

variable {C J A : Over (Spec (.of K))} [GrpObj J] [GrpObj A]

/-- **Uniqueness in the Albanese universal property, among homomorphisms.**  Let
`φ : C ⟶ J` be the Abel–Jacobi map of a curve `C` into an abelian variety `J`, and suppose
the iterated sums of `φ` *generate* `J`: for some finite family `c : Fin n → (W ⟶ C)` the
sum-morphism `∏ᵢ (c i ≫ φ) : W ⟶ J` is (topologically) dominant.  (This is the geometric
content that the Jacobian is generated by the curve — the Tower-B input; the integrator
instantiates `W = Cⁿ`, `c = projections`, dominance from Jacobi inversion / Riemann–Roch.)
Then any two group homomorphisms `g₁ g₂ : J ⟶ A` to a (commutative) abelian variety `A`
that agree after `φ` are equal. -/
theorem albanese_uniqueness [IsCommMonObj J] [IsCommMonObj A] [IsReduced J.left] [IsProper A.hom]
    (φ : C ⟶ J) {g₁ g₂ : J ⟶ A} [IsMonHom g₁] [IsMonHom g₂]
    (hφ : φ ≫ g₁ = φ ≫ g₂)
    {n : ℕ} {W : Over (Spec (.of K))} (c : Fin n → (W ⟶ C))
    (hdom : IsDominant (∏ i, c i ≫ φ).left) : g₁ = g₂ := by
  haveI := hdom
  refine hom_ext_of_isDominant (∏ i, c i ≫ φ) ?_
  have key : ∀ i : Fin n, (c i ≫ φ) ≫ g₁ = (c i ≫ φ) ≫ g₂ := fun i => by
    rw [Category.assoc, Category.assoc, hφ]
  have e₁ := map_prod (postcompHom g₁ W) (fun i => c i ≫ φ) Finset.univ
  have e₂ := map_prod (postcompHom g₂ W) (fun i => c i ≫ φ) Finset.univ
  simp only [postcompHom_apply] at e₁ e₂
  rw [e₁, e₂]
  exact Finset.prod_congr rfl (fun i _ => key i)

attribute [local instance] isCommMonObj_of_isProper_of_geometricallyIntegral

/-- **The uniqueness half of hole 9, for arbitrary morphisms.**  In the universal property
`∃! g, f = ofCurve P ≫ g` the witness `g` ranges over *all* morphisms `Jacobian C ⟶ A`,
not only homomorphisms.  But every `g` satisfying the factorization is automatically
*pointed* — `η[J] ≫ g = P ≫ f = η[A]`, using `hφ : P ≫ φ = η[J]` (the `comp_ofCurve`
property, hole 8) and `hf : P ≫ f = η[A]` — hence a group homomorphism by **Mumford
rigidity** (round 1, `isMonHom_of_pointed_of_geometricallyIntegral`).  Two such `g₁ g₂`
then coincide by `albanese_uniqueness`.  This is the full uniqueness side of hole 9: the
only un-discharged input is the geometric *generation* `hdom` (Tower B). -/
theorem albanese_uniqueness_of_pointed_factorization
    [IsProper J.hom] [GeometricallyIntegral J.hom] [IsReduced J.left]
    [IsProper A.hom] [GeometricallyIntegral A.hom]
    {P : 𝟙_ (Over (Spec (.of K))) ⟶ C} {φ : C ⟶ J} (hφ : P ≫ φ = η[J])
    {f : C ⟶ A} (hf : P ≫ f = η[A])
    {g₁ g₂ : J ⟶ A} (hg₁ : f = φ ≫ g₁) (hg₂ : f = φ ≫ g₂)
    {n : ℕ} {W : Over (Spec (.of K))} (c : Fin n → (W ⟶ C))
    (hdom : IsDominant (∏ i, c i ≫ φ).left) : g₁ = g₂ := by
  -- every factorization is pointed: `η[J] ≫ g = P ≫ φ ≫ g = P ≫ f = η[A]`.
  have hp₁ : η[J] ≫ g₁ = η[A] := by rw [← hφ, Category.assoc, ← hg₁, hf]
  have hp₂ : η[J] ≫ g₂ = η[A] := by rw [← hφ, Category.assoc, ← hg₂, hf]
  -- pointed ⟹ homomorphism (Mumford rigidity).
  haveI : IsMonHom g₁ := isMonHom_of_pointed_of_geometricallyIntegral J A g₁ hp₁
  haveI : IsMonHom g₂ := isMonHom_of_pointed_of_geometricallyIntegral J A g₂ hp₂
  exact albanese_uniqueness φ (by rw [← hg₁, ← hg₂]) c hdom

end AbelianVariety
